/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupplierRouteImport } from './routes/supplier'
import { Route as PengaturanRouteImport } from './routes/pengaturan'
import { Route as PembelianRouteImport } from './routes/pembelian'
import { Route as PelangganRouteImport } from './routes/pelanggan'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdukIndexRouteImport } from './routes/produk.index'
import { Route as PesananIndexRouteImport } from './routes/pesanan.index'
import { Route as GudangIndexRouteImport } from './routes/gudang.index'
import { Route as ProdukTambahRouteImport } from './routes/produk.tambah'
import { Route as ProdukNonaktifRouteImport } from './routes/produk.nonaktif'
import { Route as ProdukMappingRouteImport } from './routes/produk.mapping'
import { Route as ProdukDraftRouteImport } from './routes/produk.draft'
import { Route as ProdukAktifRouteImport } from './routes/produk.aktif'
import { Route as PesananSiapDiprosesRouteImport } from './routes/pesanan.siap-diproses'
import { Route as PesananSelesaiRouteImport } from './routes/pesanan.selesai'
import { Route as PesananReturRouteImport } from './routes/pesanan.retur'
import { Route as PesananPickingRouteImport } from './routes/pesanan.picking'
import { Route as PesananPackingRouteImport } from './routes/pesanan.packing'
import { Route as PesananMenungguPickupRouteImport } from './routes/pesanan.menunggu-pickup'
import { Route as PesananMenungguDibayarRouteImport } from './routes/pesanan.menunggu-dibayar'
import { Route as MarketplaceTokopediaRouteImport } from './routes/marketplace.tokopedia'
import { Route as MarketplaceTiktokRouteImport } from './routes/marketplace.tiktok'
import { Route as MarketplaceShopeeRouteImport } from './routes/marketplace.shopee'
import { Route as MarketplaceLazadaRouteImport } from './routes/marketplace.lazada'
import { Route as GudangTransferRouteImport } from './routes/gudang.transfer'
import { Route as GudangStockRouteImport } from './routes/gudang.stock'
import { Route as GudangPenyesuaianRouteImport } from './routes/gudang.penyesuaian'
import { Route as GudangOpnameRouteImport } from './routes/gudang.opname'
import { Route as GudangMasukRouteImport } from './routes/gudang.masuk'
import { Route as GudangKeluarRouteImport } from './routes/gudang.keluar'

const SupplierRoute = SupplierRouteImport.update({
  id: '/supplier',
  path: '/supplier',
  getParentRoute: () => rootRouteImport,
} as any)
const PengaturanRoute = PengaturanRouteImport.update({
  id: '/pengaturan',
  path: '/pengaturan',
  getParentRoute: () => rootRouteImport,
} as any)
const PembelianRoute = PembelianRouteImport.update({
  id: '/pembelian',
  path: '/pembelian',
  getParentRoute: () => rootRouteImport,
} as any)
const PelangganRoute = PelangganRouteImport.update({
  id: '/pelanggan',
  path: '/pelanggan',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukIndexRoute = ProdukIndexRouteImport.update({
  id: '/produk/',
  path: '/produk/',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananIndexRoute = PesananIndexRouteImport.update({
  id: '/pesanan/',
  path: '/pesanan/',
  getParentRoute: () => rootRouteImport,
} as any)
const GudangIndexRoute = GudangIndexRouteImport.update({
  id: '/gudang/',
  path: '/gudang/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukTambahRoute = ProdukTambahRouteImport.update({
  id: '/produk/tambah',
  path: '/produk/tambah',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukNonaktifRoute = ProdukNonaktifRouteImport.update({
  id: '/produk/nonaktif',
  path: '/produk/nonaktif',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukMappingRoute = ProdukMappingRouteImport.update({
  id: '/produk/mapping',
  path: '/produk/mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukDraftRoute = ProdukDraftRouteImport.update({
  id: '/produk/draft',
  path: '/produk/draft',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdukAktifRoute = ProdukAktifRouteImport.update({
  id: '/produk/aktif',
  path: '/produk/aktif',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananSiapDiprosesRoute = PesananSiapDiprosesRouteImport.update({
  id: '/pesanan/siap-diproses',
  path: '/pesanan/siap-diproses',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananSelesaiRoute = PesananSelesaiRouteImport.update({
  id: '/pesanan/selesai',
  path: '/pesanan/selesai',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananReturRoute = PesananReturRouteImport.update({
  id: '/pesanan/retur',
  path: '/pesanan/retur',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananPickingRoute = PesananPickingRouteImport.update({
  id: '/pesanan/picking',
  path: '/pesanan/picking',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananPackingRoute = PesananPackingRouteImport.update({
  id: '/pesanan/packing',
  path: '/pesanan/packing',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananMenungguPickupRoute = PesananMenungguPickupRouteImport.update({
  id: '/pesanan/menunggu-pickup',
  path: '/pesanan/menunggu-pickup',
  getParentRoute: () => rootRouteImport,
} as any)
const PesananMenungguDibayarRoute = PesananMenungguDibayarRouteImport.update({
  id: '/pesanan/menunggu-dibayar',
  path: '/pesanan/menunggu-dibayar',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceTokopediaRoute = MarketplaceTokopediaRouteImport.update({
  id: '/marketplace/tokopedia',
  path: '/marketplace/tokopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceTiktokRoute = MarketplaceTiktokRouteImport.update({
  id: '/marketplace/tiktok',
  path: '/marketplace/tiktok',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceShopeeRoute = MarketplaceShopeeRouteImport.update({
  id: '/marketplace/shopee',
  path: '/marketplace/shopee',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceLazadaRoute = MarketplaceLazadaRouteImport.update({
  id: '/marketplace/lazada',
  path: '/marketplace/lazada',
  getParentRoute: () => rootRouteImport,
} as any)
const GudangTransferRoute = GudangTransferRouteImport.update({
  id: '/gudang/transfer',
  path: '/gudang/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const GudangStockRoute = GudangStockRouteImport.update({
  id: '/gudang/stock',
  path: '/gudang/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const GudangPenyesuaianRoute = GudangPenyesuaianRouteImport.update({
  id: '/gudang/penyesuaian',
  path: '/gudang/penyesuaian',
  getParentRoute: () => rootRouteImport,
} as any)
const GudangOpnameRoute = GudangOpnameRouteImport.update({
  id: '/gudang/opname',
  path: '/gudang/opname',
  getParentRoute: () => rootRouteImport,
} as any)
const GudangMasukRoute = GudangMasukRouteImport.update({
  id: '/gudang/masuk',
  path: '/gudang/masuk',
  getParentRoute: () => rootRouteImport,
} as any)
const GudangKeluarRoute = GudangKeluarRouteImport.update({
  id: '/gudang/keluar',
  path: '/gudang/keluar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pelanggan': typeof PelangganRoute
  '/pembelian': typeof PembelianRoute
  '/pengaturan': typeof PengaturanRoute
  '/supplier': typeof SupplierRoute
  '/gudang/keluar': typeof GudangKeluarRoute
  '/gudang/masuk': typeof GudangMasukRoute
  '/gudang/opname': typeof GudangOpnameRoute
  '/gudang/penyesuaian': typeof GudangPenyesuaianRoute
  '/gudang/stock': typeof GudangStockRoute
  '/gudang/transfer': typeof GudangTransferRoute
  '/marketplace/lazada': typeof MarketplaceLazadaRoute
  '/marketplace/shopee': typeof MarketplaceShopeeRoute
  '/marketplace/tiktok': typeof MarketplaceTiktokRoute
  '/marketplace/tokopedia': typeof MarketplaceTokopediaRoute
  '/pesanan/menunggu-dibayar': typeof PesananMenungguDibayarRoute
  '/pesanan/menunggu-pickup': typeof PesananMenungguPickupRoute
  '/pesanan/packing': typeof PesananPackingRoute
  '/pesanan/picking': typeof PesananPickingRoute
  '/pesanan/retur': typeof PesananReturRoute
  '/pesanan/selesai': typeof PesananSelesaiRoute
  '/pesanan/siap-diproses': typeof PesananSiapDiprosesRoute
  '/produk/aktif': typeof ProdukAktifRoute
  '/produk/draft': typeof ProdukDraftRoute
  '/produk/mapping': typeof ProdukMappingRoute
  '/produk/nonaktif': typeof ProdukNonaktifRoute
  '/produk/tambah': typeof ProdukTambahRoute
  '/gudang/': typeof GudangIndexRoute
  '/pesanan/': typeof PesananIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pelanggan': typeof PelangganRoute
  '/pembelian': typeof PembelianRoute
  '/pengaturan': typeof PengaturanRoute
  '/supplier': typeof SupplierRoute
  '/gudang/keluar': typeof GudangKeluarRoute
  '/gudang/masuk': typeof GudangMasukRoute
  '/gudang/opname': typeof GudangOpnameRoute
  '/gudang/penyesuaian': typeof GudangPenyesuaianRoute
  '/gudang/stock': typeof GudangStockRoute
  '/gudang/transfer': typeof GudangTransferRoute
  '/marketplace/lazada': typeof MarketplaceLazadaRoute
  '/marketplace/shopee': typeof MarketplaceShopeeRoute
  '/marketplace/tiktok': typeof MarketplaceTiktokRoute
  '/marketplace/tokopedia': typeof MarketplaceTokopediaRoute
  '/pesanan/menunggu-dibayar': typeof PesananMenungguDibayarRoute
  '/pesanan/menunggu-pickup': typeof PesananMenungguPickupRoute
  '/pesanan/packing': typeof PesananPackingRoute
  '/pesanan/picking': typeof PesananPickingRoute
  '/pesanan/retur': typeof PesananReturRoute
  '/pesanan/selesai': typeof PesananSelesaiRoute
  '/pesanan/siap-diproses': typeof PesananSiapDiprosesRoute
  '/produk/aktif': typeof ProdukAktifRoute
  '/produk/draft': typeof ProdukDraftRoute
  '/produk/mapping': typeof ProdukMappingRoute
  '/produk/nonaktif': typeof ProdukNonaktifRoute
  '/produk/tambah': typeof ProdukTambahRoute
  '/gudang': typeof GudangIndexRoute
  '/pesanan': typeof PesananIndexRoute
  '/produk': typeof ProdukIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/pelanggan': typeof PelangganRoute
  '/pembelian': typeof PembelianRoute
  '/pengaturan': typeof PengaturanRoute
  '/supplier': typeof SupplierRoute
  '/gudang/keluar': typeof GudangKeluarRoute
  '/gudang/masuk': typeof GudangMasukRoute
  '/gudang/opname': typeof GudangOpnameRoute
  '/gudang/penyesuaian': typeof GudangPenyesuaianRoute
  '/gudang/stock': typeof GudangStockRoute
  '/gudang/transfer': typeof GudangTransferRoute
  '/marketplace/lazada': typeof MarketplaceLazadaRoute
  '/marketplace/shopee': typeof MarketplaceShopeeRoute
  '/marketplace/tiktok': typeof MarketplaceTiktokRoute
  '/marketplace/tokopedia': typeof MarketplaceTokopediaRoute
  '/pesanan/menunggu-dibayar': typeof PesananMenungguDibayarRoute
  '/pesanan/menunggu-pickup': typeof PesananMenungguPickupRoute
  '/pesanan/packing': typeof PesananPackingRoute
  '/pesanan/picking': typeof PesananPickingRoute
  '/pesanan/retur': typeof PesananReturRoute
  '/pesanan/selesai': typeof PesananSelesaiRoute
  '/pesanan/siap-diproses': typeof PesananSiapDiprosesRoute
  '/produk/aktif': typeof ProdukAktifRoute
  '/produk/draft': typeof ProdukDraftRoute
  '/produk/mapping': typeof ProdukMappingRoute
  '/produk/nonaktif': typeof ProdukNonaktifRoute
  '/produk/tambah': typeof ProdukTambahRoute
  '/gudang/': typeof GudangIndexRoute
  '/pesanan/': typeof PesananIndexRoute
  '/produk/': typeof ProdukIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/laporan'
    | '/login'
    | '/pelanggan'
    | '/pembelian'
    | '/pengaturan'
    | '/supplier'
    | '/gudang/keluar'
    | '/gudang/masuk'
    | '/gudang/opname'
    | '/gudang/penyesuaian'
    | '/gudang/stock'
    | '/gudang/transfer'
    | '/marketplace/lazada'
    | '/marketplace/shopee'
    | '/marketplace/tiktok'
    | '/marketplace/tokopedia'
    | '/pesanan/menunggu-dibayar'
    | '/pesanan/menunggu-pickup'
    | '/pesanan/packing'
    | '/pesanan/picking'
    | '/pesanan/retur'
    | '/pesanan/selesai'
    | '/pesanan/siap-diproses'
    | '/produk/aktif'
    | '/produk/draft'
    | '/produk/mapping'
    | '/produk/nonaktif'
    | '/produk/tambah'
    | '/gudang/'
    | '/pesanan/'
    | '/produk/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/laporan'
    | '/login'
    | '/pelanggan'
    | '/pembelian'
    | '/pengaturan'
    | '/supplier'
    | '/gudang/keluar'
    | '/gudang/masuk'
    | '/gudang/opname'
    | '/gudang/penyesuaian'
    | '/gudang/stock'
    | '/gudang/transfer'
    | '/marketplace/lazada'
    | '/marketplace/shopee'
    | '/marketplace/tiktok'
    | '/marketplace/tokopedia'
    | '/pesanan/menunggu-dibayar'
    | '/pesanan/menunggu-pickup'
    | '/pesanan/packing'
    | '/pesanan/picking'
    | '/pesanan/retur'
    | '/pesanan/selesai'
    | '/pesanan/siap-diproses'
    | '/produk/aktif'
    | '/produk/draft'
    | '/produk/mapping'
    | '/produk/nonaktif'
    | '/produk/tambah'
    | '/gudang'
    | '/pesanan'
    | '/produk'
  id:
    | '__root__'
    | '/'
    | '/laporan'
    | '/login'
    | '/pelanggan'
    | '/pembelian'
    | '/pengaturan'
    | '/supplier'
    | '/gudang/keluar'
    | '/gudang/masuk'
    | '/gudang/opname'
    | '/gudang/penyesuaian'
    | '/gudang/stock'
    | '/gudang/transfer'
    | '/marketplace/lazada'
    | '/marketplace/shopee'
    | '/marketplace/tiktok'
    | '/marketplace/tokopedia'
    | '/pesanan/menunggu-dibayar'
    | '/pesanan/menunggu-pickup'
    | '/pesanan/packing'
    | '/pesanan/picking'
    | '/pesanan/retur'
    | '/pesanan/selesai'
    | '/pesanan/siap-diproses'
    | '/produk/aktif'
    | '/produk/draft'
    | '/produk/mapping'
    | '/produk/nonaktif'
    | '/produk/tambah'
    | '/gudang/'
    | '/pesanan/'
    | '/produk/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaporanRoute: typeof LaporanRoute
  LoginRoute: typeof LoginRoute
  PelangganRoute: typeof PelangganRoute
  PembelianRoute: typeof PembelianRoute
  PengaturanRoute: typeof PengaturanRoute
  SupplierRoute: typeof SupplierRoute
  GudangKeluarRoute: typeof GudangKeluarRoute
  GudangMasukRoute: typeof GudangMasukRoute
  GudangOpnameRoute: typeof GudangOpnameRoute
  GudangPenyesuaianRoute: typeof GudangPenyesuaianRoute
  GudangStockRoute: typeof GudangStockRoute
  GudangTransferRoute: typeof GudangTransferRoute
  MarketplaceLazadaRoute: typeof MarketplaceLazadaRoute
  MarketplaceShopeeRoute: typeof MarketplaceShopeeRoute
  MarketplaceTiktokRoute: typeof MarketplaceTiktokRoute
  MarketplaceTokopediaRoute: typeof MarketplaceTokopediaRoute
  PesananMenungguDibayarRoute: typeof PesananMenungguDibayarRoute
  PesananMenungguPickupRoute: typeof PesananMenungguPickupRoute
  PesananPackingRoute: typeof PesananPackingRoute
  PesananPickingRoute: typeof PesananPickingRoute
  PesananReturRoute: typeof PesananReturRoute
  PesananSelesaiRoute: typeof PesananSelesaiRoute
  PesananSiapDiprosesRoute: typeof PesananSiapDiprosesRoute
  ProdukAktifRoute: typeof ProdukAktifRoute
  ProdukDraftRoute: typeof ProdukDraftRoute
  ProdukMappingRoute: typeof ProdukMappingRoute
  ProdukNonaktifRoute: typeof ProdukNonaktifRoute
  ProdukTambahRoute: typeof ProdukTambahRoute
  GudangIndexRoute: typeof GudangIndexRoute
  PesananIndexRoute: typeof PesananIndexRoute
  ProdukIndexRoute: typeof ProdukIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/supplier': {
      id: '/supplier'
      path: '/supplier'
      fullPath: '/supplier'
      preLoaderRoute: typeof SupplierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pengaturan': {
      id: '/pengaturan'
      path: '/pengaturan'
      fullPath: '/pengaturan'
      preLoaderRoute: typeof PengaturanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pembelian': {
      id: '/pembelian'
      path: '/pembelian'
      fullPath: '/pembelian'
      preLoaderRoute: typeof PembelianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelanggan': {
      id: '/pelanggan'
      path: '/pelanggan'
      fullPath: '/pelanggan'
      preLoaderRoute: typeof PelangganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/': {
      id: '/produk/'
      path: '/produk'
      fullPath: '/produk/'
      preLoaderRoute: typeof ProdukIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan/': {
      id: '/pesanan/'
      path: '/pesanan'
      fullPath: '/pesanan/'
      preLoaderRoute: typeof PesananIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gudang/': {
      id: '/gudang/'
      path: '/gudang'
      fullPath: '/gudang/'
      preLoaderRoute: typeof GudangIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/tambah': {
      id: '/produk/tambah'
      path: '/produk/tambah'
      fullPath: '/produk/tambah'
      preLoaderRoute: typeof ProdukTambahRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/nonaktif': {
      id: '/produk/nonaktif'
      path: '/produk/nonaktif'
      fullPath: '/produk/nonaktif'
      preLoaderRoute: typeof ProdukNonaktifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/mapping': {
      id: '/produk/mapping'
      path: '/produk/mapping'
      fullPath: '/produk/mapping'
      preLoaderRoute: typeof ProdukMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/draft': {
      id: '/produk/draft'
      path: '/produk/draft'
      fullPath: '/produk/draft'
      preLoaderRoute: typeof ProdukDraftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produk/aktif': {
      id: '/produk/aktif'
      path: '/produk/aktif'
      fullPath: '/produk/aktif'
      preLoaderRoute: typeof ProdukAktifRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan/siap-diproses': {
      id: '/pesanan/siap-diproses'
      path: '/pesanan/siap-diproses'
      fullPath: '/pesanan/siap-diproses'
      preLoaderRoute: typeof PesananSiapDiprosesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan/selesai': {
      id: '/pesanan/selesai'
      path: '/pesanan/selesai'
      fullPath: '/pesanan/selesai'
      preLoaderRoute: typeof PesananSelesaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan/retur': {
      id: '/pesanan/retur'
      path: '/pesanan/retur'
      fullPath: '/pesanan/retur'
      preLoaderRoute: typeof PesananReturRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan/picking': {
      id: '/pesanan/picking'
      path: '/pesanan/picking'
      fullPath: '/pesanan/picking'
      preLoaderRoute: typeof PesananPickingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan/packing': {
      id: '/pesanan/packing'
      path: '/pesanan/packing'
      fullPath: '/pesanan/packing'
      preLoaderRoute: typeof PesananPackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan/menunggu-pickup': {
      id: '/pesanan/menunggu-pickup'
      path: '/pesanan/menunggu-pickup'
      fullPath: '/pesanan/menunggu-pickup'
      preLoaderRoute: typeof PesananMenungguPickupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pesanan/menunggu-dibayar': {
      id: '/pesanan/menunggu-dibayar'
      path: '/pesanan/menunggu-dibayar'
      fullPath: '/pesanan/menunggu-dibayar'
      preLoaderRoute: typeof PesananMenungguDibayarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/tokopedia': {
      id: '/marketplace/tokopedia'
      path: '/marketplace/tokopedia'
      fullPath: '/marketplace/tokopedia'
      preLoaderRoute: typeof MarketplaceTokopediaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/tiktok': {
      id: '/marketplace/tiktok'
      path: '/marketplace/tiktok'
      fullPath: '/marketplace/tiktok'
      preLoaderRoute: typeof MarketplaceTiktokRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/shopee': {
      id: '/marketplace/shopee'
      path: '/marketplace/shopee'
      fullPath: '/marketplace/shopee'
      preLoaderRoute: typeof MarketplaceShopeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/lazada': {
      id: '/marketplace/lazada'
      path: '/marketplace/lazada'
      fullPath: '/marketplace/lazada'
      preLoaderRoute: typeof MarketplaceLazadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gudang/transfer': {
      id: '/gudang/transfer'
      path: '/gudang/transfer'
      fullPath: '/gudang/transfer'
      preLoaderRoute: typeof GudangTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gudang/stock': {
      id: '/gudang/stock'
      path: '/gudang/stock'
      fullPath: '/gudang/stock'
      preLoaderRoute: typeof GudangStockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gudang/penyesuaian': {
      id: '/gudang/penyesuaian'
      path: '/gudang/penyesuaian'
      fullPath: '/gudang/penyesuaian'
      preLoaderRoute: typeof GudangPenyesuaianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gudang/opname': {
      id: '/gudang/opname'
      path: '/gudang/opname'
      fullPath: '/gudang/opname'
      preLoaderRoute: typeof GudangOpnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gudang/masuk': {
      id: '/gudang/masuk'
      path: '/gudang/masuk'
      fullPath: '/gudang/masuk'
      preLoaderRoute: typeof GudangMasukRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gudang/keluar': {
      id: '/gudang/keluar'
      path: '/gudang/keluar'
      fullPath: '/gudang/keluar'
      preLoaderRoute: typeof GudangKeluarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaporanRoute: LaporanRoute,
  LoginRoute: LoginRoute,
  PelangganRoute: PelangganRoute,
  PembelianRoute: PembelianRoute,
  PengaturanRoute: PengaturanRoute,
  SupplierRoute: SupplierRoute,
  GudangKeluarRoute: GudangKeluarRoute,
  GudangMasukRoute: GudangMasukRoute,
  GudangOpnameRoute: GudangOpnameRoute,
  GudangPenyesuaianRoute: GudangPenyesuaianRoute,
  GudangStockRoute: GudangStockRoute,
  GudangTransferRoute: GudangTransferRoute,
  MarketplaceLazadaRoute: MarketplaceLazadaRoute,
  MarketplaceShopeeRoute: MarketplaceShopeeRoute,
  MarketplaceTiktokRoute: MarketplaceTiktokRoute,
  MarketplaceTokopediaRoute: MarketplaceTokopediaRoute,
  PesananMenungguDibayarRoute: PesananMenungguDibayarRoute,
  PesananMenungguPickupRoute: PesananMenungguPickupRoute,
  PesananPackingRoute: PesananPackingRoute,
  PesananPickingRoute: PesananPickingRoute,
  PesananReturRoute: PesananReturRoute,
  PesananSelesaiRoute: PesananSelesaiRoute,
  PesananSiapDiprosesRoute: PesananSiapDiprosesRoute,
  ProdukAktifRoute: ProdukAktifRoute,
  ProdukDraftRoute: ProdukDraftRoute,
  ProdukMappingRoute: ProdukMappingRoute,
  ProdukNonaktifRoute: ProdukNonaktifRoute,
  ProdukTambahRoute: ProdukTambahRoute,
  GudangIndexRoute: GudangIndexRoute,
  PesananIndexRoute: PesananIndexRoute,
  ProdukIndexRoute: ProdukIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
